In [144]:
import warnings
warnings.filterwarnings("ignore")

In [145]:
import datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [146]:
from datasets import load_dataset
import pandas as pd
ds=load_dataset("Tobi-Bueck/customer-support-tickets")

In [147]:
df=pd.DataFrame(ds['train'])
df.to_csv("data.csv")

KeyboardInterrupt:

In [ ]:
df=df[['body','queue','language']]
df.head()

,body,queue,language
0,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Technical Support,de
1,"Dear Customer Support Team,\n\nI am writing to...",Technical Support,en
2,"Dear Customer Support Team,\n\nI hope this mes...",Returns and Exchanges,en
3,"Dear Customer Support Team,\n\nI hope this mes...",Billing and Payments,en
4,"Dear Support Team,\n\nI hope this message reac...",Sales and Pre-Sales,en

In [ ]:
df['body'].isnull().sum()
df['body']=df['body'].fillna("")
df['body']=df['body'].fillna("").str.lower()

In [ ]:
import re

df['body']=df['body'].apply(lambda x: re.sub(r'nn+',' ',x))
df['body']=df['body'].apply(lambda x: re.sub(r'\s+', ' ',x).strip())
df['body']=df['body'].apply(lambda x: re.sub(r'([a-z])([A-Z])',r'\1 \2',x))

In [ ]:
import re
import string

df['body']=df['body'].apply(lambda x: re.sub(r'[^\w\s]', '', x))

In [ ]:
import nltk
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
from nltk.tokenize import word_tokenize
df['tokens']=df['body'].apply(word_tokenize)
df.head()

,body,queue,language,tokens
0,sehr geehrtes supportteamnnich möchte einen gr...,Technical Support,de,"[sehr, geehrtes, supportteamnnich, möchte, ein..."
1,dear customer support teamnni am writing to re...,Technical Support,en,"[dear, customer, support, teamnni, am, writing..."
2,dear customer support teamnni hope this messag...,Returns and Exchanges,en,"[dear, customer, support, teamnni, hope, this,..."
3,dear customer support teamnni hope this messag...,Billing and Payments,en,"[dear, customer, support, teamnni, hope, this,..."
4,dear support teamnni hope this message reaches...,Sales and Pre-Sales,en,"[dear, support, teamnni, hope, this, message, ..."

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

english=set(stopwords.words('english'))
german=set(stopwords.words('german'))

df['tokens']=df['tokens'].apply(
    lambda words:[w.lower() for w in words if w.isalpha()]
)
df.loc[df['language'] == 'en', 'tokens'] = df.loc[df['language'] == 'en', 'tokens'].apply(
    lambda words: [w for w in words if w not in english]
)

df.loc[df['language'] == 'de', 'tokens'] = df.loc[df['language'] == 'de', 'tokens'].apply(
    lambda words: [w for w in words if w not in german]
)

df.head()

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

,body,queue,language,tokens
0,sehr geehrtes supportteamnnich möchte einen gr...,Technical Support,de,"[geehrtes, supportteamnnich, möchte, gravieren..."
1,dear customer support teamnni am writing to re...,Technical Support,en,"[dear, customer, support, teamnni, writing, re..."
2,dear customer support teamnni hope this messag...,Returns and Exchanges,en,"[dear, customer, support, teamnni, hope, messa..."
3,dear customer support teamnni hope this messag...,Billing and Payments,en,"[dear, customer, support, teamnni, hope, messa..."
4,dear support teamnni hope this message reaches...,Sales and Pre-Sales,en,"[dear, support, teamnni, hope, message, reache..."

In [ ]:
df['tokens']=df['tokens'].apply(lambda words:[w.lower() for w in words])
df.head()

,body,queue,language,tokens
0,sehr geehrtes supportteamnnich möchte einen gr...,Technical Support,de,"[geehrtes, supportteamnnich, möchte, gravieren..."
1,dear customer support teamnni am writing to re...,Technical Support,en,"[dear, customer, support, teamnni, writing, re..."
2,dear customer support teamnni hope this messag...,Returns and Exchanges,en,"[dear, customer, support, teamnni, hope, messa..."
3,dear customer support teamnni hope this messag...,Billing and Payments,en,"[dear, customer, support, teamnni, hope, messa..."
4,dear support teamnni hope this message reaches...,Sales and Pre-Sales,en,"[dear, support, teamnni, hope, message, reache..."

In [ ]:
df['tokens']=df['tokens'].apply(lambda words: [w for w in words if w.isalpha()])
df['tokens'].head()

0    [geehrtes, supportteamnnich, möchte, gravieren...
1    [dear, customer, support, teamnni, writing, re...
2    [dear, customer, support, teamnni, hope, messa...
3    [dear, customer, support, teamnni, hope, messa...
4    [dear, support, teamnni, hope, message, reache...
Name: tokens, dtype: object

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [ ]:
from nltk.stem import WordNetLemmatizer

lemma=WordNetLemmatizer()
df['tokens']=df['tokens'].apply(
    lambda words:[lemma.lemmatize(w) for w in words]
)
df.head()

,body,queue,language,tokens
0,sehr geehrtes supportteamnnich möchte einen gr...,Technical Support,de,"[geehrtes, supportteamnnich, möchte, gravieren..."
1,dear customer support teamnni am writing to re...,Technical Support,en,"[dear, customer, support, teamnni, writing, re..."
2,dear customer support teamnni hope this messag...,Returns and Exchanges,en,"[dear, customer, support, teamnni, hope, messa..."
3,dear customer support teamnni hope this messag...,Billing and Payments,en,"[dear, customer, support, teamnni, hope, messa..."
4,dear support teamnni hope this message reaches...,Sales and Pre-Sales,en,"[dear, support, teamnni, hope, message, reach,..."

In [ ]:
df['tokens']=df['tokens'].apply(lambda words: " ".join(words))

In [ ]:
print(df.columns)

Index(['body', 'queue', 'language', 'tokens'], dtype='object')

In [ ]:
x=df['tokens']
y=df['queue']

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(max_features=5000)
x_train_vec=tfidf.fit_transform(X_train)
X_test_vec = tfidf.transform(X_test)

In [ ]:
df.to_csv("clean_data.csv")

In [ ]:
df = ds['train'].to_pandas()

In [ ]:
from sklearn.linear_model import LogisticRegression
m1=LogisticRegression(max_iter=1000,class_weight='balanced')
m1.fit(x_train_vec,y_train)
y_pred=m1.predict(X_test_vec)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7173965838257913
Classification Report:
                                         precision    recall  f1-score   support

           Arts & Entertainment/Movies       0.98      0.78      0.87        54
            Arts & Entertainment/Music       0.87      0.71      0.79        77
          Autos & Vehicles/Maintenance       0.67      0.76      0.71        62
                Autos & Vehicles/Sales       0.65      0.70      0.67        66
            Beauty & Fitness/Cosmetics       0.80      0.85      0.82        55
     Beauty & Fitness/Fitness Training       0.88      0.70      0.78        60
                  Billing and Payments       0.94      0.78      0.85       990
            Books & Literature/Fiction       0.64      0.75      0.69        52
        Books & Literature/Non-Fiction       0.80      0.78      0.79        63
   Business & Industrial/Manufacturing       0.75      0.74      0.74        73
                      Customer Service       0.67      0.67      0.67      1460
                   Finance/Investments       0.87      0.89      0.88        66
              Finance/Personal Finance       0.80      0.74      0.77        54
                Food & Drink/Groceries       0.78      0.72      0.75        71
              Food & Drink/Restaurants       0.83      0.72      0.77        60
                                 Games       0.86      0.76      0.81        67
                       General Inquiry       0.85      0.48      0.61       128
               Health/Medical Services       0.74      0.81      0.77        83
                  Health/Mental Health       0.90      0.93      0.91        67
        Hobbies & Leisure/Collectibles       0.89      0.78      0.83        64
              Hobbies & Leisure/Crafts       0.86      0.68      0.76        75
        Home & Garden/Home Improvement       0.82      0.76      0.79        66
             Home & Garden/Landscaping       0.78      0.71      0.75        56
                       Human Resources       0.97      0.52      0.68       193
      IT & Technology/Hardware Support       0.83      0.79      0.81        63
IT & Technology/Network Infrastructure       0.85      0.88      0.86        50
   IT & Technology/Security Operations       0.77      0.83      0.80        66
  IT & Technology/Software Development       0.90      0.92      0.91        59
                            IT Support       0.94      0.52      0.67      1092
       Jobs & Education/Online Courses       0.82      0.69      0.75        81
          Jobs & Education/Recruitment       0.92      0.87      0.90        55
  Law & Government/Government Services       0.85      0.84      0.85        76
         Law & Government/Legal Advice       0.78      0.75      0.77        53
                                  News       0.76      0.74      0.75        82
             Online Communities/Forums       0.89      0.92      0.90        76
    Online Communities/Social Networks       0.84      0.81      0.82        72
    People & Society/Culture & Society       0.66      0.64      0.65        45
           Pets & Animals/Pet Services       0.78      0.75      0.77        76
        Pets & Animals/Veterinary Care       0.93      0.78      0.84        80
                       Product Support       0.76      0.59      0.66      1794
                           Real Estate       0.85      0.68      0.76        41
                 Returns and Exchanges       0.97      0.51      0.67       531
                   Sales and Pre-Sales       0.91      0.52      0.66       282
         Science/Environmental Science       0.76      0.73      0.75        56
                      Science/Research       0.86      0.65      0.74        65
       Service Outages and Maintenance       0.94      0.61      0.74       368
                   Shopping/E-commerce       0.87      0.87      0.87        60
                Shopping/Retail Stores       0.84      0.87      0.85        54
                                Sports       0.89      0.67      0.76        51
                     Technical Support       0.56      0.92      0.69      2846
    Travel & Transportation/Air Travel       0.79      0.79      0.79        52
   Travel & Transportation/Land Travel       0.80      0.72      0.76        65

                              accuracy                           0.72     12353
                             macro avg       0.83      0.74      0.77     12353
                          weighted avg       0.77      0.72      0.72     12353

F1 Score: 0.7175723620249309
Confusion Matrix:
 [[  42    1    0 ...    4    0    0]
 [   0   55    2 ...    5    0    2]
 [   0    0   47 ...    3    0    0]
 ...
 [   0    0    0 ... 2623    0    0]
 [   0    0    1 ...    2   41    0]
 [   0    0    1 ...    4    1   47]]

In [ ]:
from sklearn.naive_bayes import MultinomialNB

m2=MultinomialNB()
m2.fit(x_train_vec,y_train)
y_pred=m2.predict(X_test_vec)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.434955071642516
Classification Report:
                                         precision    recall  f1-score   support

           Arts & Entertainment/Movies       0.95      0.37      0.53        54
            Arts & Entertainment/Music       1.00      0.27      0.43        77
          Autos & Vehicles/Maintenance       0.77      0.27      0.40        62
                Autos & Vehicles/Sales       0.39      0.68      0.49        66
            Beauty & Fitness/Cosmetics       0.73      0.55      0.62        55
     Beauty & Fitness/Fitness Training       0.93      0.42      0.57        60
                  Billing and Payments       0.88      0.56      0.69       990
            Books & Literature/Fiction       0.72      0.50      0.59        52
        Books & Literature/Non-Fiction       0.52      0.67      0.58        63
   Business & Industrial/Manufacturing       0.62      0.71      0.66        73
                      Customer Service       0.28      0.45      0.34      1460
                   Finance/Investments       0.90      0.67      0.77        66
              Finance/Personal Finance       0.52      0.70      0.60        54
                Food & Drink/Groceries       0.78      0.51      0.62        71
              Food & Drink/Restaurants       0.92      0.38      0.54        60
                                 Games       0.83      0.36      0.50        67
                       General Inquiry       1.00      0.01      0.02       128
               Health/Medical Services       0.54      0.61      0.57        83
                  Health/Mental Health       0.60      0.88      0.72        67
        Hobbies & Leisure/Collectibles       0.41      0.59      0.49        64
              Hobbies & Leisure/Crafts       0.61      0.49      0.54        75
        Home & Garden/Home Improvement       0.47      0.74      0.58        66
             Home & Garden/Landscaping       1.00      0.16      0.28        56
                       Human Resources       1.00      0.01      0.01       193
      IT & Technology/Hardware Support       0.85      0.63      0.73        63
IT & Technology/Network Infrastructure       0.87      0.68      0.76        50
   IT & Technology/Security Operations       0.44      0.88      0.59        66
  IT & Technology/Software Development       0.89      0.66      0.76        59
                            IT Support       0.45      0.03      0.05      1092
       Jobs & Education/Online Courses       0.75      0.59      0.66        81
          Jobs & Education/Recruitment       0.95      0.73      0.82        55
  Law & Government/Government Services       0.78      0.67      0.72        76
         Law & Government/Legal Advice       0.74      0.43      0.55        53
                                  News       0.26      0.93      0.41        82
             Online Communities/Forums       0.86      0.89      0.88        76
    Online Communities/Social Networks       0.79      0.36      0.50        72
    People & Society/Culture & Society       0.79      0.33      0.47        45
           Pets & Animals/Pet Services       0.27      0.64      0.38        76
        Pets & Animals/Veterinary Care       0.60      0.68      0.64        80
                       Product Support       0.35      0.21      0.26      1794
                           Real Estate       0.80      0.10      0.17        41
                 Returns and Exchanges       0.92      0.02      0.04       531
                   Sales and Pre-Sales       0.25      0.01      0.02       282
         Science/Environmental Science       0.54      0.70      0.61        56
                      Science/Research       0.74      0.45      0.56        65
       Service Outages and Maintenance       0.88      0.06      0.12       368
                   Shopping/E-commerce       0.63      0.90      0.74        60
                Shopping/Retail Stores       0.94      0.59      0.73        54
                                Sports       1.00      0.12      0.21        51
                     Technical Support       0.40      0.77      0.52      2846
    Travel & Transportation/Air Travel       0.82      0.44      0.57        52
   Travel & Transportation/Land Travel       0.41      0.48      0.44        65

                              accuracy                           0.43     12353
                             macro avg       0.70      0.49      0.50     12353
                          weighted avg       0.53      0.43      0.39     12353

F1 Score: 0.3887050892289721
Confusion Matrix:
 [[  20    0    0 ...    0    0    0]
 [   1   21    0 ...    1    0    1]
 [   0    0   17 ...    0    0    1]
 ...
 [   0    0    0 ... 2197    0    0]
 [   0    0    1 ...    2   23    2]
 [   0    0    0 ...    2    1   31]]

In [ ]:
from sklearn.svm import LinearSVC

m3=LinearSVC()
m3.fit(x_train_vec,y_train)
y_pred=m3.predict(X_test_vec)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.5465069213956124
Classification Report:
                                         precision    recall  f1-score   support

           Arts & Entertainment/Movies       0.85      0.76      0.80        54
            Arts & Entertainment/Music       0.76      0.75      0.76        77
          Autos & Vehicles/Maintenance       0.58      0.58      0.58        62
                Autos & Vehicles/Sales       0.62      0.67      0.64        66
            Beauty & Fitness/Cosmetics       0.77      0.80      0.79        55
     Beauty & Fitness/Fitness Training       0.81      0.63      0.71        60
                  Billing and Payments       0.77      0.71      0.74       990
            Books & Literature/Fiction       0.75      0.69      0.72        52
        Books & Literature/Non-Fiction       0.75      0.81      0.78        63
   Business & Industrial/Manufacturing       0.85      0.78      0.81        73
                      Customer Service       0.40      0.40      0.40      1460
                   Finance/Investments       0.92      0.86      0.89        66
              Finance/Personal Finance       0.80      0.80      0.80        54
                Food & Drink/Groceries       0.78      0.65      0.71        71
              Food & Drink/Restaurants       0.71      0.70      0.71        60
                                 Games       0.75      0.76      0.76        67
                       General Inquiry       0.55      0.21      0.31       128
               Health/Medical Services       0.72      0.72      0.72        83
                  Health/Mental Health       0.94      0.91      0.92        67
        Hobbies & Leisure/Collectibles       0.77      0.69      0.73        64
              Hobbies & Leisure/Crafts       0.83      0.71      0.76        75
        Home & Garden/Home Improvement       0.70      0.68      0.69        66
             Home & Garden/Landscaping       0.74      0.77      0.75        56
                       Human Resources       0.74      0.31      0.43       193
      IT & Technology/Hardware Support       0.82      0.89      0.85        63
IT & Technology/Network Infrastructure       0.88      0.90      0.89        50
   IT & Technology/Security Operations       0.68      0.88      0.77        66
  IT & Technology/Software Development       0.95      0.92      0.93        59
                            IT Support       0.38      0.27      0.32      1092
       Jobs & Education/Online Courses       0.89      0.77      0.82        81
          Jobs & Education/Recruitment       0.89      0.85      0.87        55
  Law & Government/Government Services       0.80      0.83      0.81        76
         Law & Government/Legal Advice       0.70      0.72      0.71        53
                                  News       0.80      0.77      0.78        82
             Online Communities/Forums       0.94      0.96      0.95        76
    Online Communities/Social Networks       0.80      0.71      0.75        72
    People & Society/Culture & Society       0.62      0.69      0.65        45
           Pets & Animals/Pet Services       0.61      0.58      0.59        76
        Pets & Animals/Veterinary Care       0.78      0.80      0.79        80
                       Product Support       0.42      0.40      0.41      1794
                           Real Estate       0.71      0.66      0.68        41
                 Returns and Exchanges       0.58      0.26      0.36       531
                   Sales and Pre-Sales       0.51      0.28      0.36       282
         Science/Environmental Science       0.61      0.77      0.68        56
                      Science/Research       0.76      0.82      0.79        65
       Service Outages and Maintenance       0.65      0.57      0.61       368
                   Shopping/E-commerce       0.80      0.93      0.86        60
                Shopping/Retail Stores       0.88      0.85      0.87        54
                                Sports       0.81      0.75      0.78        51
                     Technical Support       0.48      0.67      0.56      2846
    Travel & Transportation/Air Travel       0.64      0.69      0.67        52
   Travel & Transportation/Land Travel       0.59      0.57      0.58        65

                              accuracy                           0.55     12353
                             macro avg       0.73      0.69      0.70     12353
                          weighted avg       0.55      0.55      0.54     12353

F1 Score: 0.5392343188124439
Confusion Matrix:
 [[  41    4    0 ...    0    0    1]
 [   0   58    2 ...    1    1    0]
 [   0    0   36 ...    1    0    0]
 ...
 [   0    0    0 ... 1907    0    0]
 [   1    0    0 ...    2   36    0]
 [   1    0    3 ...    1    2   37]]

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)

weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))

In [ ]:
from sklearn.ensemble import RandomForestClassifier

m4=RandomForestClassifier(class_weight=class_weights)
m4.fit(x_train_vec,y_train)
y_pred=m4.predict(X_test_vec)

In [ ]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,f1_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.7173965838257913
Classification Report:
                                         precision    recall  f1-score   support

           Arts & Entertainment/Movies       0.98      0.78      0.87        54
            Arts & Entertainment/Music       0.87      0.71      0.79        77
          Autos & Vehicles/Maintenance       0.67      0.76      0.71        62
                Autos & Vehicles/Sales       0.65      0.70      0.67        66
            Beauty & Fitness/Cosmetics       0.80      0.85      0.82        55
     Beauty & Fitness/Fitness Training       0.88      0.70      0.78        60
                  Billing and Payments       0.94      0.78      0.85       990
            Books & Literature/Fiction       0.64      0.75      0.69        52
        Books & Literature/Non-Fiction       0.80      0.78      0.79        63
   Business & Industrial/Manufacturing       0.75      0.74      0.74        73
                      Customer Service       0.67      0.67      0.67      1460
                   Finance/Investments       0.87      0.89      0.88        66
              Finance/Personal Finance       0.80      0.74      0.77        54
                Food & Drink/Groceries       0.78      0.72      0.75        71
              Food & Drink/Restaurants       0.83      0.72      0.77        60
                                 Games       0.86      0.76      0.81        67
                       General Inquiry       0.85      0.48      0.61       128
               Health/Medical Services       0.74      0.81      0.77        83
                  Health/Mental Health       0.90      0.93      0.91        67
        Hobbies & Leisure/Collectibles       0.89      0.78      0.83        64
              Hobbies & Leisure/Crafts       0.86      0.68      0.76        75
        Home & Garden/Home Improvement       0.82      0.76      0.79        66
             Home & Garden/Landscaping       0.78      0.71      0.75        56
                       Human Resources       0.97      0.52      0.68       193
      IT & Technology/Hardware Support       0.83      0.79      0.81        63
IT & Technology/Network Infrastructure       0.85      0.88      0.86        50
   IT & Technology/Security Operations       0.77      0.83      0.80        66
  IT & Technology/Software Development       0.90      0.92      0.91        59
                            IT Support       0.94      0.52      0.67      1092
       Jobs & Education/Online Courses       0.82      0.69      0.75        81
          Jobs & Education/Recruitment       0.92      0.87      0.90        55
  Law & Government/Government Services       0.85      0.84      0.85        76
         Law & Government/Legal Advice       0.78      0.75      0.77        53
                                  News       0.76      0.74      0.75        82
             Online Communities/Forums       0.89      0.92      0.90        76
    Online Communities/Social Networks       0.84      0.81      0.82        72
    People & Society/Culture & Society       0.66      0.64      0.65        45
           Pets & Animals/Pet Services       0.78      0.75      0.77        76
        Pets & Animals/Veterinary Care       0.93      0.78      0.84        80
                       Product Support       0.76      0.59      0.66      1794
                           Real Estate       0.85      0.68      0.76        41
                 Returns and Exchanges       0.97      0.51      0.67       531
                   Sales and Pre-Sales       0.91      0.52      0.66       282
         Science/Environmental Science       0.76      0.73      0.75        56
                      Science/Research       0.86      0.65      0.74        65
       Service Outages and Maintenance       0.94      0.61      0.74       368
                   Shopping/E-commerce       0.87      0.87      0.87        60
                Shopping/Retail Stores       0.84      0.87      0.85        54
                                Sports       0.89      0.67      0.76        51
                     Technical Support       0.56      0.92      0.69      2846
    Travel & Transportation/Air Travel       0.79      0.79      0.79        52
   Travel & Transportation/Land Travel       0.80      0.72      0.76        65

                              accuracy                           0.72     12353
                             macro avg       0.83      0.74      0.77     12353
                          weighted avg       0.77      0.72      0.72     12353

F1 Score: 0.7175723620249309
Confusion Matrix:
 [[  42    1    0 ...    4    0    0]
 [   0   55    2 ...    5    0    2]
 [   0    0   47 ...    3    0    0]
 ...
 [   0    0    0 ... 2623    0    0]
 [   0    0    1 ...    2   41    0]
 [   0    0    1 ...    4    1   47]]

In [ ]:
import pickle

with open("model1.pkl","wb") as f:
  pickle.dump((m4,tfidf),f)

In [169]:
text=df['tokens']

In [172]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
tokenizer = Tokenizer(num_words=20000,oov_token="<OOV>")
tokenizer.fit_on_texts(text)
sequences = tokenizer.texts_to_sequences(text)
pad=pad_sequences(sequences,maxlen=150,padding='post',truncating='post')

from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(df['queue'])

In [173]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    pad,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras import Sequential
from tensorflow.keras.layers import LSTM, Dense, Bidirectional,Dropout
from tensorflow.keras.optimizers import Adam # Import Adam optimizer

num_classes=len(set(y))
model=Sequential()

# Set input_length to 50 to match maxlen used in pad_sequences
model.add(Embedding(input_dim=5000+1,output_dim=150,input_length=60))
model.add(Bidirectional(LSTM(128, return_sequences=False)))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dense(num_classes,activation='softmax'))

# Use 'sparse_categorical_crossentropy' with integer labels
model.compile(loss='sparse_categorical_crossentropy', optimizer=Adam(learning_rate=0.001),metrics=['accuracy'])

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=2,
    restore_best_weights=True
)

In [ ]:
from tensorflow.keras.callbacks import ReduceLROnPlateau

lr_reduce = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.3,
    patience=1,
    min_lr=1e-5
)

In [ ]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train_lstm),
    y=y_train_lstm
)

class_weights = dict(zip(np.unique(y_train_lstm), class_weights))

In [ ]:
model.fit(
    x_train_lstm,
    y_train_lstm,
    epochs=10,
    batch_size=16,
    validation_data=(x_test_lstm, y_test_lstm),
    callbacks=[early_stop, lr_reduce],
    # class_weight=class_weights
)

Epoch 1/10
 557/3089 ━━━━━━━━━━━━━━━━━━━━ 33s 13ms/step - accuracy: 0.2009 - loss: 2.6383

In [ ]:
model.save("lstm_model.keras")

In [ ]:
import pickle

with open("lstm.pkl","wb") as f:
  pickle.dump(tokenizer, f)

In [ ]:
model.summary()

NameError: name 'model' is not defined

In [ ]:
from sklearn.metrics import accuracy_score,classification_report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

In [ ]:
df['tokens'] = df['tokens'].apply(lambda x: x.split())

In [ ]:
print(df['tokens'].head())

0    [geehrtes, supportteamnnich, möchte, gravieren...
1    [dear, customer, support, teamnni, writing, re...
2    [dear, customer, support, teamnni, hope, messa...
3    [dear, customer, support, teamnni, hope, messa...
4    [dear, support, teamnni, hope, message, reach,...
Name: tokens, dtype: object

In [ ]:
unique_words = set()

for tokens in df['tokens']:
    unique_words.update(tokens)

print("Total Unique Words:", len(unique_words))

Total Unique Words: 48836

In [174]:
from collections import Counter

counter = Counter()

for tokens in df['tokens']:
    counter.update(tokens)

# Vocabulary dictionary
vocab = {
    '<PAD>': 0,
    '<UNK>': 1
}

# Add words to vocab
for word, freq in counter.items():

    # Keep words appearing at least 2 times
    if freq >= 2:
        vocab[word] = len(vocab)

vocab_size = len(vocab)

print("Vocabulary Size:", vocab_size)

Vocabulary Size: 28204

In [ ]:
!pip install datasets nltk scikit-learn torch

Requirement already satisfied: datasets in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (4.8.4)
Requirement already satisfied: nltk in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (3.9.4)
Requirement already satisfied: scikit-learn in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (1.7.2)
Collecting torch
  Using cached torch-2.11.0-cp310-cp310-win_amd64.whl (114.5 MB)
Requirement already satisfied: pyarrow>=21.0.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (23.0.1)
Requirement already satisfied: multiprocess<0.70.20 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (0.70.19)
Requirement already satisfied: fsspec[http]<=2026.2.0,>=2023.1.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (2026.2.0)
Requirement already satisfied: packaging in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (26.0)
Requirement already satisfied: numpy>=1.17 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (0.4.1)
Requirement already satisfied: pandas in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (2.3.3)
Requirement already satisfied: filelock in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (3.25.2)
Requirement already satisfied: requests>=2.32.2 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (2.33.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (1.9.0)
Requirement already satisfied: httpx<1.0.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (6.0.3)
Requirement already satisfied: tqdm>=4.66.3 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from datasets) (3.6.0)
Requirement already satisfied: click in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: regex>=2021.8.3 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from nltk) (2026.4.4)
Requirement already satisfied: joblib in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: scipy>=1.8.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from scikit-learn) (1.15.3)
Collecting sympy>=1.13.3
  Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Requirement already satisfied: setuptools<82 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from torch) (65.5.0)
Collecting networkx>=2.5.1
  Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: jinja2 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: certifi in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from httpx<1.0.0->datasets) (2026.4.22)
Requirement already satisfied: anyio in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from httpx<1.0.0->datasets) (4.13.0)
Requirement already satisfied: idna in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from httpx<1.0.0->datasets) (3.13)
Requirement already satisfied: httpcore==1.* in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.4.3)
Requirement already satisfied: typer in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (0.24.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from requests>=2.32.2->datasets) (2.6.3)
Collecting mpmath<1.4,>=1.1.0
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ---------------------------------------- 0.0/536.2 kB ? eta -:--:--
      --------------------------------------- 10.2/536.2 kB ? eta -:--:--
     -- ---------------------------------- 41.0/536.2 kB 393.8 kB/s eta 0:00:02
     ---- -------------------------------- 71.7/536.2 kB 438.9 kB/s eta 0:00:02
     ------ ----------------------------- 102.4/536.2 kB 535.8 kB/s eta 0:00:01
     --------- -------------------------- 143.4/536.2 kB 568.9 kB/s eta 0:00:01
     --------- -------------------------- 143.4/536.2 kB 568.9 kB/s eta 0:00:01
     ---------- ------------------------- 153.6/536.2 kB 482.7 kB/s eta 0:00:01
     ----------- ------------------------ 174.1/536.2 kB 476.3 kB/s eta 0:00:01
     ------------ ----------------------- 184.3/536.2 kB 446.4 kB/s eta 0:00:01
     ------------- ---------------------- 204.8/536.2 kB 445.2 kB/s eta 0:00:01
     --------------- -------------------- 225.3/536.2 kB 458.5 kB/s eta 0:00:01
     --------------- -------------------- 235.5/536.2 kB 437.4 kB/s eta 0:00:01
     ----------------- ------------------ 256.0/536.2 kB 437.3 kB/s eta 0:00:01
     ----------------- ------------------ 266.2/536.2 kB 420.4 kB/s eta 0:00:01
     -------------------- --------------- 307.2/536.2 kB 452.7 kB/s eta 0:00:01
     --------------------- -------------- 317.4/536.2 kB 437.0 kB/s eta 0:00:01
     ---------------------- ------------- 327.7/536.2 kB 415.0 kB/s eta 0:00:01
     ----------------------- ------------ 348.2/536.2 kB 416.2 kB/s eta 0:00:01
     ------------------------ ----------- 368.6/536.2 kB 417.2 kB/s eta 0:00:01
     -------------------------- --------- 389.1/536.2 kB 418.2 kB/s eta 0:00:01
     -------------------------- --------- 399.4/536.2 kB 415.3 kB/s eta 0:00:01
     ---------------------------- ------- 430.1/536.2 kB 426.7 kB/s eta 0:00:01
     ---------------------------- ------- 430.1/536.2 kB 426.7 kB/s eta 0:00:01
     ------------------------------- ---- 471.0/536.2 kB 421.2 kB/s eta 0:00:01
     --------------------------------- -- 501.8/536.2 kB 431.2 kB/s eta 0:00:01
     ---------------------------------- - 512.0/536.2 kB 428.1 kB/s eta 0:00:01
     -----------------------------------  532.5/536.2 kB 428.4 kB/s eta 0:00:01
     ------------------------------------ 536.2/536.2 kB 426.2 kB/s eta 0:00:00
Requirement already satisfied: colorama in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: pytz>=2020.1 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: attrs>=17.3.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: propcache>=0.2.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: six>=1.5 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.0.4)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (2.19.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (4.0.0)
Requirement already satisfied: mdurl~=0.1 in c:\aiml\projects\brickview real estate project\venv310\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub<2.0,>=0.25.0->datasets) (0.1.2)
Installing collected packages: mpmath, sympy, networkx, torch
Successfully installed mpmath-1.3.0 networkx-3.4.2 sympy-1.14.0 torch-2.11.0

WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\aiml\projects\brickview real estate project\venv310\lib\site-packages)

[notice] A new release of pip is available: 23.0.1 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from collections import Counter

In [175]:
class LSTMClassifier(nn.Module):

    def __init__(self,
                 vocab_size,
                 embedding_dim,
                 hidden_dim,
                 output_dim,
                 num_layers=2,
                 dropout=0.3):

        super(LSTMClassifier, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)

        self.lstm = nn.LSTM(
            embedding_dim,
            hidden_dim,
            num_layers=num_layers,
            batch_first=True,
            dropout=dropout,
            bidirectional=True
        )

        self.fc = nn.Linear(hidden_dim * 2, output_dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        embedded = self.embedding(x)

        lstm_out, (hidden, cell) = self.lstm(embedded)

        # Concatenate forward + backward hidden states
        hidden = torch.cat((hidden[-2], hidden[-1]), dim=1)

        hidden = self.dropout(hidden)

        output = self.fc(hidden)

        return output

In [161]:
from torch.utils.data import Dataset, DataLoader
import torch

class TicketDataset(Dataset):

    def __init__(self, X, y):

        self.X = torch.tensor(X, dtype=torch.long)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):

        return len(self.X)

    def __getitem__(self, idx):

        return self.X[idx], self.y[idx]

In [176]:
train_dataset = TicketDataset(X_train, y_train)

test_dataset = TicketDataset(X_test, y_test)

In [177]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32
)

In [ ]:
num_classes = len(le.classes_)

print(num_classes)

52

In [178]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

num_classes=52

model = LSTMClassifier(
    vocab_size=vocab_size,
    embedding_dim=128,
    hidden_dim=128,
    output_dim=num_classes
)

model = model.to(device)

print(model)

LSTMClassifier(
  (embedding): Embedding(28204, 128, padding_idx=0)
  (lstm): LSTM(128, 128, num_layers=2, batch_first=True, dropout=0.3, bidirectional=True)
  (fc): Linear(in_features=256, out_features=52, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
)

In [179]:
from sklearn.utils.class_weight import compute_class_weight

class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(y_train),
    y=y_train
)

# Convert to tensor
class_weights = torch.tensor(
    class_weights,
    dtype=torch.float
).to(device)

# Loss function with class weights
criterion = nn.CrossEntropyLoss(
    weight=class_weights
)


optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

In [ ]:
num_epochs = 18

for epoch in range(num_epochs):

    model.train()

    total_loss = 0

    for texts, labels in train_loader:

        texts = texts.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        outputs = model(texts)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)

    print(f"Epoch [{epoch+1}/{num_epochs}], Loss: {avg_loss:.4f}")

Epoch [1/18], Loss: 2.5668
Epoch [2/18], Loss: 1.9036
Epoch [3/18], Loss: 1.3605

In [167]:
model.eval()

predictions = []
actuals = []

with torch.no_grad():

    for texts, labels in test_loader:

        texts = texts.to(device)

        outputs = model(texts)

        _, preds = torch.max(outputs, 1)

        predictions.extend(preds.cpu().numpy())

        actuals.extend(labels.numpy())

In [168]:
accuracy = accuracy_score(actuals, predictions)

print("Accuracy:", accuracy)

print(classification_report(actuals, predictions))

Accuracy: 0.5010928519388003
              precision    recall  f1-score   support

           0       0.32      0.44      0.37        54
           1       0.15      0.16      0.15        77
           2       0.13      0.18      0.15        62
           3       0.18      0.29      0.22        66
           4       0.29      0.25      0.27        55
           5       0.20      0.22      0.21        60
           6       0.85      0.72      0.78       990
           7       0.28      0.46      0.35        52
           8       0.48      0.32      0.38        63
           9       0.25      0.40      0.31        73
          10       0.50      0.49      0.50      1460
          11       0.29      0.23      0.25        66
          12       0.56      0.61      0.58        54
          13       0.18      0.18      0.18        71
          14       0.14      0.13      0.14        60
          15       0.29      0.13      0.18        67
          16       0.55      0.26      0.35       128
          17       0.26      0.23      0.24        83
          18       0.51      0.52      0.52        67
          19       0.27      0.31      0.29        64
          20       0.25      0.19      0.22        75
          21       0.23      0.18      0.20        66
          22       0.29      0.21      0.25        56
          23       0.40      0.23      0.30       193
          24       0.52      0.44      0.48        63
          25       0.41      0.24      0.30        50
          26       0.30      0.44      0.36        66
          27       0.61      0.64      0.63        59
          28       0.42      0.56      0.48      1092
          29       0.26      0.19      0.22        81
          30       0.30      0.13      0.18        55
          31       0.36      0.36      0.36        76
          32       0.18      0.30      0.22        53
          33       0.26      0.28      0.27        82
          34       0.73      0.78      0.75        76
          35       0.20      0.25      0.22        72
          36       0.20      0.22      0.21        45
          37       0.32      0.28      0.30        76
          38       0.29      0.14      0.19        80
          39       0.52      0.49      0.50      1794
          40       0.15      0.24      0.19        41
          41       0.59      0.36      0.45       531
          42       0.45      0.29      0.35       282
          43       0.28      0.39      0.33        56
          44       0.32      0.11      0.16        65
          45       0.57      0.61      0.59       368
          46       0.60      0.50      0.55        60
          47       0.43      0.52      0.47        54
          48       0.23      0.24      0.23        51
          49       0.60      0.67      0.63      2846
          50       0.23      0.21      0.22        52
          51       0.25      0.20      0.22        65

    accuracy                           0.50     12353
   macro avg       0.35      0.33      0.34     12353
weighted avg       0.51      0.50      0.50     12353